### ISSUE TITLE
我们是否可以合作？

### ISSUE THREAD

**Issue by demohi** [camsong/redux-in-chinese#1]
Hi，[我们](https://github.com/redux-cn)也准备翻译redux的[中文文档](https://github.com/redux-cn/redux)，看到你也在翻译，我觉得我们可以一起合作

另外我们注册了 [reduxjs.com](http://reduxjs.com/)这个域名，也方便后续使用。: )

**Comment by camsong** [comment]
看了你的博客，感觉你研究 Redux 也有一段时间了，这方面的经验可以多多交流。
现在还有很多章节待翻译，我正在整理翻译准则，在保证质量的同时，也急切希望能有人一起分担翻译和审校工作。等文档质量达到一定水平后会以 GitHub Group 协作的形式来做这个事情。

**Comment by demohi** [comment]
@camsong  等翻译准则出来之后，可以联系我  ：）

**Comment by camsong** [comment]
翻译准备已更新到 README.md
https://github.com/camsong/redux-in-chinese/tree/master#加入翻译

**Comment by gaearon** [comment]
@demohi 

We'd really appreciate you pointing `reduxjs.com` to point to the official Redux docs instead. The beginners are looking at the outdated and incomplete docs and they assume those are official because of the domain name :-(. Let's discuss this in https://github.com/rackt/redux/issues/890?

**Comment by hsin421** [comment]
@demohi 
Redux作者本人想請你將 reduxjs.com 網址指向 redux.js.org，因為目前reduxjs.com上面的版本已經落後正版，這樣會讓初學者困擾
希望你能夠提供協助
