### ISSUE TITLE
关于章节2.5 Usage with React中的疑问

### ISSUE THREAD

**Issue by hashtree** [camsong/redux-in-chinese#112]
章节2.5中 Presentational and Container Components 那一段的中文翻译，为什么会加上下面这一句呢？

> “明智的做法是只在最顶层组件（如路由操作）里使用 Redux”

同样的，在下方的表格中也提到容器组件的location应该在

> “最顶层”

对比了英文版，其实并没有这样的说法。所以很想知道它是否是大神自己的最佳实践？为什么会得到这样的结论？

中英截屏对比
![snapshot1](https://cloud.githubusercontent.com/assets/5159758/14699665/3c14c696-07cc-11e6-8ccb-abf19dc7f768.png)
![snapshot2](https://cloud.githubusercontent.com/assets/5159758/14699668/3fc1d90a-07cc-11e6-8423-c65f82f016a8.png)

望大神不吝赐教，谢谢

**Comment by jovey-zheng** [comment]
@hashtree 是因为没有更新文档。
如果有时间的话我们会组织人员进行更新，当然如果你能协助更新那更是欢迎！

**Comment by hashtree** [comment]
好呀，刚才看了下ETC翻译规范，并未要求最小翻译单位。那我可以针对这一段直接提交小修改罗。

**Comment by jovey-zheng** [comment]
@hashtree nice job

**Comment by camsong** [comment]
很好的建议，我们已经发起了新一轮的文档同步项目，有时间欢迎参与贡献 v3.0 👊
