### ISSUE TITLE
文档同步：【介绍】章节

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#113]
介绍章节

https://github.com/reactjs/redux/blob/master/docs/introduction/README.md

- [ ] Motivation https://github.com/reactjs/redux/blob/master/docs/introduction/Motivation.md
- [ ] https://github.com/reactjs/redux/blob/master/docs/introduction/ThreePrinciples.md
- [ ] https://github.com/reactjs/redux/blob/master/docs/introduction/PriorArt.md
- [ ] https://github.com/reactjs/redux/blob/master/docs/introduction/Ecosystem.md
- [ ] https://github.com/reactjs/redux/blob/master/docs/introduction/Examples.md

**Comment by yuweiw823** [comment]
I'll do it :)

On Thu, Apr 21, 2016 at 7:30 PM, Cam Song <notifications@github.com> wrote:

> 介绍章节
>
> https://github.com/reactjs/redux/blob/master/docs/introduction/README.md
>
>    - Motivation
>    https://github.com/reactjs/redux/blob/master/docs/introduction/Motivation.md
>    -
>    https://github.com/reactjs/redux/blob/master/docs/introduction/ThreePrinciples.md
>    -
>    https://github.com/reactjs/redux/blob/master/docs/introduction/PriorArt.md
>    -
>    https://github.com/reactjs/redux/blob/master/docs/introduction/Ecosystem.md
>    -
>    https://github.com/reactjs/redux/blob/master/docs/introduction/Examples.md
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/camsong/redux-in-chinese/issues/113>
>



-- 
*Yuwei WANG*
Software Developer
University of Washington
yuweiw823@gmail.com | (206) 941-4907 | LinkedIn Profile
<https://www.linkedin.com/in/yuweiw823>

**Comment by yuweiw823** [comment]
PR requested. Please review :)

**Comment by camsong** [comment]
Awesome @yuweiw823. fixed by https://github.com/camsong/redux-in-chinese/pull/128
