### ISSUE TITLE
文档同步：【基础】前三章节

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#114]
阶段性同步，回复即可认领。

原文链接：
- [ ] https://github.com/reactjs/redux/blob/master/docs/basics/Actions.md
- [ ] https://github.com/reactjs/redux/blob/master/docs/basics/Reducers.md
- [ ] https://github.com/reactjs/redux/blob/master/docs/basics/Store.md

**Comment by hashtree** [comment]
I'll take it.
