### ISSUE TITLE
2.2节的疑问

### ISSUE THREAD

**Issue by Zhangjd** [camsong/redux-in-chinese#122]
[翻译文档](http://cn.redux.js.org/docs/basics/Reducers.html) 中，是否出现了 `COMPLETE_TODO` 和 `TOGGLE_TODO` 混淆的情况? 比如:

最后，COMPLETE_TODO 的实现也很好理解：

```javascript
case TOGGLE_TODO:
  return Object.assign({}, state, {
    todos: state.todos.map((todo, index) => {
      if (index === action.index) {
        return Object.assign({}, todo, {
          completed: !todo.completed
        })
      }
      return todo
    })
  })
```

英文文档中, 这一节貌似没有提及 `TOGGLE_TODO`

**Comment by camsong** [comment]
这是因为文档没有同步，麻烦 @hashtree 更新一下 https://github.com/camsong/redux-in-chinese/commit/550f4e08b81b9d420bc65a476158644279f81898

**Comment by hashtree** [comment]
收到，我今天晚些时候就处理。
