### ISSUE TITLE
todoApp 跑哪里去了

### ISSUE THREAD

**Issue by yunji7** [camsong/redux-in-chinese#130]
import React from 'react'
import { render } from 'react-dom'
import { createStore } from 'redux'
import { Provider } from 'react-redux'
import App from './containers/App'
import todoApp from './reducers'

let store = createStore(todoApp);

let rootElement = document.getElementById('root')
render(
  <Provider store={store}>
    <App />
  </Provider>,
  rootElement
)

http://cn.redux.js.org/docs/basics/UsageWithReact.html

**Comment by camsong** [comment]
在 Reducers 章节 http://cn.redux.js.org/docs/basics/Reducers.html
