### ISSUE TITLE
3.4 搭配 React Router 文档没有了？

### ISSUE THREAD

**Issue by marsrandy** [camsong/redux-in-chinese#131]
3.高级 -> 3.4 搭配 React Router 文档没有了？

http://cn.redux.js.org/docs/advanced/UsageWithReactRouter.html

**Comment by camsong** [comment]
因为原文还没有写，直接使用 https://github.com/reactjs/react-router-redux

**Comment by creamidea** [comment]
Hi, camsong. 
[3.4搭配 React Router](http://redux.js.org/docs/advanced/UsageWithReactRouter.html) 出现了，我这几天比较有空，我想试着翻译一下，你看看可以不？是我单独开一个issue？还是你开好了分配给我？

:D

**Comment by camsong** [comment]
不用开新 issue，直接翻译好后提个 PR 吧，欢迎贡献 👏
