### ISSUE TITLE
redux到底有没有dispatcher ？

### ISSUE THREAD

**Issue by OUZICHENG** [camsong/redux-in-chinese#136]
本人新手，因为学习react的缘故，从他们的英文文档里看到了redux。搜索之后发现了中文文档，非常赞，感谢大家的努力工作。
我看到两个地方有相互矛盾的地方，不太理解，冒昧问下：
在文档的先前技术章节：http://cn.redux.js.org/docs/introduction/PriorArt.html
中说到flux 时说“而不同于 Flux ，Redux 并没有 dispatcher 的概念”
在文档基础action章节：http://cn.redux.js.org/docs/basics/Actions.html
中说“一般来说你会通过 store.dispatch() 将 action 传到 store。”

dispatcher的概念和store.dispatch() 有木有联系，还是只是看着相似，望有高手解答。

再次感谢

**Comment by pandazki** [comment]
我的理解是这样的：
flux 里面的 dispatcher 是一个独立的分发器实体，每个 store 需要向 dispatcher 注册才能被分发到关心的数据，一般是基于事件处理器实现。
redux 里面没有采用这种方式，而是通过纯函数来替代事件处理器，而且是单一 store，因此 store 自身就可以完成 action 分发这个过程。

**Comment by OUZICHENG** [comment]
所以说我是否可以这样理解，FLUX与REDUX的主要区别还是在于前者使用多store，后者使用单个store .
所以分发数据方面，前者使用一个叫dispatcher 的实体类来完成，而后者也有类似的分发功能，只是不再是一个类，而是一个函数，碰巧名字也使用了dispatch这个单词。

**Comment by OUZICHENG** [comment]
@pandazki 谢谢
