### ISSUE TITLE
文档有误

### ISSUE THREAD

**Issue by riskers** [camsong/redux-in-chinese#147]
`basics/ExampleTodoList.md`: 

containers/App.js 中

``` js
import { addTodo, completeTodo, setVisibilityFilter, VisibilityFilters } from '../actions'
```

应是

``` js
import { addTodo, toggleTodo, setVisibilityFilter, VisibilityFilters } from '../actions';
```

TodoList的 completeTodo 也应是 toggleTodo

初学 redux，这是我自己发现的，应该是笔误，比较简单，就不pr了。

**Comment by camsong** [comment]
Good catch 👏  发现有很多内容过期了，能否做个 PR，把这一章节同步一下。原文：https://github.com/reactjs/redux/blob/master/docs/basics/ExampleTodoList.md

**Comment by CallMeXYZ** [comment]
同问 为什么和官方的文档差距这么大？例子的思想也不一样。是中文文档版本落后还是超前了？

**Comment by CallMeXYZ** [comment]
中文文档和英文文档不一样啊，中文文档是基于什么（版本）翻译的啊？

**Comment by CallMeXYZ** [comment]
文档过时太久了，比如`basics/UsageWithReact.md`里还是沿用开始的文档，建议`connect()`操作放在顶部组件，但是根据后来的[Issue](https://github.com/reactjs/redux/issues/419)，至少是不建议的。强烈建议及时更新文档，以及其中例子，不然很影响读者啊

**Comment by logzh** [comment]
https://github.com/camsong/redux-in-chinese/blob/master/docs/advanced/UsageWithReactRouter.md#componentsappjs

文档有误 components/App.js 应该是 containers/VisibleTodoList.js

http://redux.js.org/docs/advanced/UsageWithReactRouter.html#containersvisibletodolistjs

**Comment by camsong** [comment]
@CallMeXYZ 更新文档的 issue 建好了，欢迎贡献
