### ISSUE TITLE
文档同步：【高级-搭配 React Router】

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#165]
文档过期了 :broken_heart: ，你来帮助同步一下吧 

原文：https://github.com/reactjs/redux/blob/master/docs/advanced/UsageWithReactRouter.md
译文：https://github.com/camsong/redux-in-chinese/blob/master/docs/advanced/UsageWithReactRouter.md

尚未认领，欢迎回复认领 :dancer:
不知如何下手？为你准备好了 [ETC 翻译规范](https://github.com/react-guide/etc#翻译规范)

**Comment by bensonlove** [comment]
claim

**Comment by rccoder** [comment]
这么久了，我来吧...

**Comment by rccoder** [comment]
Done: https://github.com/camsong/redux-in-chinese/pull/223
