### ISSUE TITLE
文档同步：【技巧-服务端渲染】

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#170]
文档过期了 :broken_heart: ，你来帮助同步一下吧 

原文：https://github.com/reactjs/redux/blob/master/docs/recipes/ServerRendering.md
译文：https://github.com/camsong/redux-in-chinese/blob/master/docs/recipes/ServerRendering.md

尚未认领，欢迎回复认领 :dancer:
不知如何下手？为你准备好了 [ETC 翻译规范](https://github.com/react-guide/etc#翻译规范)

**Comment by xiaokk06** [comment]
我想试试  刚好开始入手redux
