### ISSUE TITLE
文档新增：【技巧-Structuring Reducers-Immutable Update Patterns】

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#185]
文档过期了 :broken_heart: ，你来帮助同步一下吧 

原文：https://github.com/reactjs/redux/blob/master/docs/recipes/reducers/ImmutableUpdatePatterns.md
译文：需要新增

尚未认领，欢迎回复认领 :dancer:
不知如何下手？为你准备好了 [ETC 翻译规范](https://github.com/react-guide/etc#翻译规范)

**Comment by ztplz** [comment]
认领

**Comment by camsong** [comment]
@ztplz any update?

**Comment by ztplz** [comment]
@camsong  sry,  忙于公司年会的事 ，没什么时间 ， 如果可以，请重新待认领吧， 很抱歉， 我的锅， 不好意思

**Comment by piaoyidage** [comment]
认领
