### ISSUE TITLE
文档同步：【API 文档-combineReducers】

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#193]
文档过期了 :broken_heart: ，你来帮助同步一下吧 

原文：https://github.com/reactjs/redux/blob/master/docs/api/combineReducers.md
译文：https://github.com/camsong/redux-in-chinese/blob/master/docs/api/combineReducers.md

尚未认领，欢迎回复认领 :dancer:
不知如何下手？为你准备好了 [ETC 翻译规范](https://github.com/react-guide/etc#翻译规范)

**Comment by rccoder** [comment]
认领
