### ISSUE TITLE
文档同步：【React Redux】

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#197]
文档过期了 :broken_heart: ，你来帮助同步一下吧 

原文：https://github.com/reactjs/react-redux/blob/master/README.md
译文：https://github.com/camsong/redux-in-chinese/blob/master/docs/react-redux/README.md

尚未认领，欢迎回复认领 :dancer:
不知如何下手？为你准备好了 [ETC 翻译规范](https://github.com/react-guide/etc#翻译规范)

**Comment by jovey-zheng** [comment]
与 #198 相同，并在 e64d4c72f291c9b19903426e699c01d05491ceea 中已更新。
