### ISSUE TITLE
关于Slice reducer的问题

### ISSUE THREAD

**Issue by mfma** [camsong/redux-in-chinese#234]
你好，我参照文档里边Reducer逻辑拆分一节的内容写了一个测试的demo,出现一个问题，如果我的reducer里使用createReducer后，我之前的的action失效了----我触发getPages这个action时发现与getPage这个action对应的reducer触发了，但是后边与getPages这个action相对于的reducer却没有反应。请问这是什么原因引起的，麻烦指导一下，谢谢。
![qq 20170217164125](https://cloud.githubusercontent.com/assets/5546094/23058454/0180af2a-f530-11e6-94a5-ed68d94e1735.png)
}

**Comment by rccoder** [comment]
@mfma  信息不全
