### ISSUE TITLE
翻译遗漏

### ISSUE THREAD

**Issue by Detachment** [camsong/redux-in-chinese#248]
由于是个小问题，就不 PR 了。

在 Reducer 这一节的 `拆分 Reducer `片段，有一句很重要的片段漏翻译了，英文原文如下：
*All combineReducers() does is generate a function that calls your reducers with the slices of state selected according to their keys, and combining their results into a single object again. It's not magic. And like other reducers, combineReducers() does not create a new object if all of the reducers provided to it do not change state.*

目前版本的翻译：
*combineReducers() 所做的只是生成一个函数，这个函数来调用你的一系列 reducer，每个 reducer 根据它们的 key 来筛选出 state 中的一部分数据并处理，然后这个生成的函数再将所有 reducer 的结果合并成一个大的对象。没有任何魔法。*

下面这句没有翻译到：
**And like other reducers, combineReducers() does not create a new object if all of the reducers provided to it do not change state.**

翻译为：
**正如其他 `reducers`，如果 `combineReducers()` 中包含的所有 `reducers` 都没有更改 `state`，那么也就不会创建一个新的对象。**

**Comment by jovey-zheng** [comment]
@Detachment 感谢回馈，如果可以的话你可以提交一个 PR 😄

**Comment by Detachment** [comment]
@jovey-zheng 已提交 PR，有时间的话去看看～
