### ISSUE TITLE
Generate Offline Docs

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#26]
生成 PDF，ePub, MOBI 电子书方便离线阅读，使用 Calibre，参照 https://github.com/paulkogel/redux-offline-docs

**Comment by demohi** [comment]
这个是单独一个项目，还是集成到现有的呢 @camsong

**Comment by camsong** [comment]
集成到现有的项目中，定期发布版本，每发一个版本就生成一下，方便下载阅读

**Comment by demohi** [comment]
:ok_hand:

**Comment by demohi** [comment]
@camsong  晚了好久 :cold_sweat:

**Comment by camsong** [comment]
👍  Better late than never
