### ISSUE TITLE
文档同步：【API-compose】

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#276]
文档过期了 :broken_heart: ，你来帮助同步一下吧

原文：https://github.com/reactjs/redux/blob/master/docs/api/compose.md
译文：https://github.com/camsong/redux-in-chinese/blob/master/docs/api/compose.md

尚未认领，欢迎回复认领 :dancer:
不知如何下手？为你准备好了 [ETC 翻译规范](https://github.com/react-guide/etc#翻译规范)

**Comment by realYukiko** [comment]
认领一下

**Comment by rccoder** [comment]
@realYukiko  👍

**Comment by realYukiko** [comment]
今天操作失误，没有用不同分支提交代码，导致两个文件的同步放在同一个PR了，https://github.com/camsong/redux-in-chinese/pull/304，事实上compose这个文件已经更新了。sorry，下次会注意。
