### ISSUE TITLE
文档同步：【API-createStore】

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#277]
文档过期了 :broken_heart: ，你来帮助同步一下吧

原文：https://github.com/reactjs/redux/blob/master/docs/api/createStore.md
译文：https://github.com/camsong/redux-in-chinese/blob/master/docs/api/createStore.md

尚未认领，欢迎回复认领 :dancer:
不知如何下手？为你准备好了 [ETC 翻译规范](https://github.com/react-guide/etc#翻译规范)

**Comment by realYukiko** [comment]
认领，谢谢！

**Comment by rccoder** [comment]
@realYukiko  OK

**Comment by realYukiko** [comment]
@rccoder 这个也已经完成了 https://github.com/camsong/redux-in-chinese/pull/302

**Comment by rccoder** [comment]
@realYukiko  应该是 applyMiddleware 吧。。

**Comment by realYukiko** [comment]
@rccoder 这个之前完成了，没有关闭issue，pr见 https://github.com/camsong/redux-in-chinese/pull/302

**Comment by realYukiko** [comment]
如果 pr 合并后，需要我来关闭issue请告知 😃
