### ISSUE TITLE
基础篇，关于Store介绍的第7行有书写错误。

### ISSUE THREAD

**Issue by woshiqiang1** [camsong/redux-in-chinese#299]
unsubscribe(listener)注销监听

**Comment by rccoder** [comment]
@woshiqiang1 欢迎提个 PR

**Comment by fralonra** [comment]
翻译没有问题，`subscribe` 方法会返回一个函数，执行该函数即可解绑监听。

**Comment by woshiqiang1** [comment]
翻译是对的，在下眼拙，源码里返回的函数的名字是unsubscribe
