### ISSUE TITLE
文档新增：【技巧-在 Redux 中使用 Immutable.JS】

### ISSUE THREAD

**Issue by rccoder** [camsong/redux-in-chinese#308]
文档过期了 :broken_heart: ，你来帮助同步一下吧

原文：https://github.com/reactjs/redux/blob/master/docs/recipes/UsingImmutableJS.md
译文：https://github.com/camsong/redux-in-chinese/blob/master/docs/recipes/UsingImmutableJS.md

尚未认领，欢迎回复认领 :dancer:
不知如何下手？为你准备好了 [ETC 翻译规范](https://github.com/react-guide/etc#翻译规范)

**Comment by QC-L** [comment]
这个是要自己添加进来吗？目前目录下没有

**Comment by rccoder** [comment]
@QC-L 嗯，新建一个吧

**Comment by QC-L** [comment]
认领~
