### ISSUE TITLE
英文单复数问题

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#31]
原文：
> First, let’s define some actions.

如果译成
> 首先，让我们来定义几个 actions。

比较符合原意，但是汉语里没有单复数概念，看起来读起来都有点奇怪。

如果译成 `action` 看起来更顺畅，但与原文不一致。

不知道业界对此类问题有没有达到共识，欢迎讨论。

**Comment by pandazki** [comment]
这个问题我也纠结过，和许多朋友讨论下来，现在我的观点是：当满足这两个条件

+ 有更符合中文习惯的句式体现出复数
+ 单词的复数没有额外的含义

时，把复数去掉，其他时候保持与原文一致。

就比如你提的例子，我更倾向于翻译为：
>首先，让我们来定义几个 action. //这里的“几个”已经体现出了复数，并且actions没有特殊的含义

但是还有一种情况，例如：
>Actions describe the fact that something happened…

现在让我翻译我会保留这个Actions：
>Actions 描述的是某些事情发生了这样的事实…… //这里Actions我感觉体现出Action这一类东西，用Action其实也通顺，但是我会选择保留s

个人意见，非语言类专业。

**Comment by camsong** [comment]
私下和几个从业的编辑聊了一下，英文单复数怎么选没有成文的条例。因为中文中没有复数之说，所以一般『全部使用单数』，除非一些极个別的情况，如『arguments』因为它本身就是一个关键字。

上例中我觉得译为『Action 描述的是某些事情发生了这样的事实』更容易理解，不然多看到 『s』还要愣一下。

**Comment by pandazki** [comment]
OK，未来就以这种方式作为约定。
