### ISSUE TITLE
利用 travis-ci 实现 gitbook 文档自动更新

### ISSUE THREAD

**Issue by rccoder** [camsong/redux-in-chinese#325]
@camsong  

目前 cn.redux.js.org 的文档需要手动去 `npm run publish` 来自动更新。

我在 https://github.com/camsong/redux-in-chinese/commit/b8760cdc80fab2b8677bcdd0499b702fe477f5e0 这个 commit 中增加了利用 travis-ci 去实现自动更新的功能。

**还需要你在 travis-ci 添加 REPO_TOKEN 的环境变量中去实现自动 Push**（如文章 https://segmentfault.com/a/1190000009054888 所示）

除此之外：
- Fix GitHub Emoji 显示问题
- Fix 语言设置问题（可能会出现繁体）
- 更新目录
- 删除了 ReadMe 中一些不太有用的东西

**Comment by camsong** [comment]
这样的自动更新非常赞，以后再也不用手动去执行部署命令了。 👏👏👏 

Token 已加
![image](https://user-images.githubusercontent.com/948896/38184475-8ec642f0-367a-11e8-9603-21ffdc5ab273.png)

**Comment by rccoder** [comment]
@camsong  试了一下已经 OK
