### ISSUE TITLE
翻译『Implementing Undo History』

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#34]
原文新加文档『Implementing Undo History』，暂无时间翻译
https://github.com/rackt/redux/blob/master/docs/recipes/ImplementingUndoHistory.md

**Comment by pandazki** [comment]
我刚好在看这个，如果没有人翻的话这周末我来搞。(∩_∩)

**Comment by camsong** [comment]
好的，assign 给你了

**Comment by camsong** [comment]
为方便协作，把你加入了 Collaborators，Welcome！

**Comment by pandazki** [comment]
已完成。
