### ISSUE TITLE
文档同步：【Recipe-UsingImmutableJS】

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#340]
文档过期了 :broken_heart: ，你来帮助同步一下吧

原文：https://github.com/reactjs/redux/blob/master/docs/recipes/UsingImmutableJS.md
译文：https://github.com/camsong/redux-in-chinese/blob/master/docs/recipes/UsingImmutableJS.md

尚未认领，欢迎回复认领 :dancer:
不知如何下手？为你准备好了 [ETC 翻译规范](https://github.com/react-guide/etc#翻译规范)

**Comment by Tommy-White** [comment]
认领： Using Immutable.JS with Redux

**Comment by wadrn** [comment]
想认领试试~

**Comment by CongLiu-CN** [comment]
请问，这个还未认领吗？因为时间是半年前了……

**Comment by camsong** [comment]
已同步 https://github.com/camsong/redux-in-chinese/pull/379
