### ISSUE TITLE
文档同步：【Recipe-ImmutableUpdatePatterns】

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#344]
文档过期了 :broken_heart: ，你来帮助同步一下吧

原文：https://github.com/reactjs/redux/blob/master/docs/recipes/reducers/ImmutableUpdatePatterns.md
译文：https://github.com/camsong/redux-in-chinese/blob/master/docs/recipes/reducers/ImmutableUpdatePatterns.md

尚未认领，欢迎回复认领 :dancer:
不知如何下手？为你准备好了 [ETC 翻译规范](https://github.com/react-guide/etc#翻译规范)

**Comment by nzhl** [comment]
认领~

**Comment by rccoder** [comment]
@nzhl  欢迎欢迎
![image](https://user-images.githubusercontent.com/7554325/46749350-1ca73800-cce8-11e8-8ad8-20a81efdb6cc.png)
