### ISSUE TITLE
引入 Prettier 格式化 Markdown 文档

### ISSUE THREAD

**Issue by froyog** [camsong/redux-in-chinese#372]
[官方仓库](https://github.com/reduxjs/redux)在 [864b9c](https://github.com/reduxjs/redux/commit/864b9c32332ca19511d5cabb0e927d340744e4fa) 已经引入了 Prettier 对 markdown 文档的格式化，主要作用是消除一些不必要的空格和空行，加入一些必要的空格和空行，保证语法一致性，以及对文档内一些 jsx 代码格式化。

如果需要的话，我可以提个 pr

**Comment by rccoder** [comment]
@froyog  OK 的
