### ISSUE TITLE
关于中文翻译中斜体的处理

### ISSUE THREAD

**Issue by jovey-zheng** [camsong/redux-in-chinese#38]
- 粗体内嵌斜体：
 > **Redux doesn’t care *how* you store the state—it can be a plain object, an Immutable object, or anything else.**
 **Redux 并不在意你*如何*存储 state，state 可以是普通对象，可以是不可变对象，或者其它类型。** 

- 正常斜体：
 > While it is technically *possible* to [write impure reducers](https://github.com/rackt/redux/issues/328#issuecomment-125035516) that mutate the data
 [写不纯的 reducers](https://github.com/gaearon/redux/issues/328#issuecomment-125035516) 来变动数据在技术上是*可行*的

对于“正常斜体”是否应该遵循[#翻译约定](https://github.com/camsong/redux-in-chinese#翻译约定)中的 ` 英文有斜体、中文没有，可用强调取代 **强调** ` 进行翻译？将 *`可行`* 译成 **`可行`**。

**Comment by camsong** [comment]
:+1: 赞成，当时译的时候没有注意，有时间的话改一下吧。
这条规则是参照这个帖子定的。http://www.zhihu.com/question/20120243
