### ISSUE TITLE
最新 redux.js 中文文档出炉： http://docs.breword.com/reduxjs-redux

### ISSUE THREAD

**Issue by 92hackers** [camsong/redux-in-chinese#390]
经过 Breword 团队一周左右的努力，总共 72+ 页文档、共 6 万+ 单词数的文档全部翻译完毕。🤩
希望能够帮助到大家：

中文文档地址为：http://docs.breword.com/reduxjs-redux

此外，文档页面提供中英文切换功能，方便想要查看英文原文的朋友，切换器详见右下角。

**Comment by vkboo** [comment]
@92hackers 你这个链接打开是一个后台管理系统啊？

**Comment by 92hackers** [comment]
https://www.breword.com/reduxjs-redux

网站经过改版，以上是最新的地址，搜索功能很强大，可以精确搜索，可以尝试一下。

tyounami <notifications@github.com> 于2021年1月18日周一 上午12:20写道：

**Comment by camsong** [comment]
Outdated!
