### ISSUE TITLE
README中的两个404

### ISSUE THREAD

**Issue by WuWaA** [camsong/redux-in-chinese#392]
> Redux 背后的 动机，核心概念 和 三大原则

因为大小写原因导致404了

核心概念
https://cn.redux.js.org/docs/introduction/coreconcepts -> https://cn.redux.js.org/docs/introduction/CoreConcepts

三大原则
https://cn.redux.js.org/docs/introduction/threeprinciples -> https://cn.redux.js.org/docs/introduction/ThreePrinciples

**Comment by camsong** [comment]
WIP
