### ISSUE TITLE
函数少了立即执行

### ISSUE THREAD

**Issue by Han3Jim** [camsong/redux-in-chinese#394]
https://cn.redux.js.org/docs/recipes/ComputingDerivedData.html#

底部最后一个函数

const VisibleTodoList = connect(
  makeMapStateToProps,
  mapDispatchToProps
)(TodoList)
应该为
const VisibleTodoList = connect(
  makeMapStateToProps(),
  mapDispatchToProps
)(TodoList)

**Comment by camsong** [comment]
Fixed
