### ISSUE TITLE
添加 react-redux『API』文档

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#47]
react-redux 虽然是独立的库，但是常经常使用，应该把文档也加入进来

原文地址：https://github.com/rackt/react-redux/blob/master/docs/api.md
译文地址：https://github.com/camsong/redux-in-chinese/blob/master/docs/react-redux/api.md

欢迎认领，直接回复即可认领

**Comment by dorayx** [comment]
我可以认领这个么 ～～～

**Comment by camsong** [comment]
可以，谢谢
