### ISSUE TITLE
添加 react-redux『quick-start』文档

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#48]
react-redux 虽然是独立的库，但是常经常使用，应该把文档也加入进来

原文地址：https://github.com/rackt/react-redux/blob/master/docs/quick-start.md
译文地址：https://github.com/camsong/redux-in-chinese/blob/master/docs/react-redux/quick-start.md

欢迎认领，直接回复即可认领

**Comment by jovey-zheng** [comment]
@camsong 我来领吧 :)

**Comment by camsong** [comment]
:+1:
