### ISSUE TITLE
添加 react-redux『troubleshooting』文档

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#49]
react-redux 虽然是独立的库，但是常经常使用，应该把文档也加入进来

原文地址：https://github.com/rackt/react-redux/blob/master/docs/troubleshooting.md
译文地址：https://github.com/camsong/redux-in-chinese/blob/master/docs/react-redux/troubleshooting.md

欢迎认领，直接回复即可认领

**Comment by jovey-zheng** [comment]
I'll do this one.
