### ISSUE TITLE
Proofread『介绍』章节

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#54]
为了译文提高质量，我们需定期对内容与原文做同步更新，本次校对的是『介绍』章节，包括 5 小节内容。

## 介绍

* [动机](https://github.com/camsong/redux-in-chinese/blob/master/docs/introduction/Motivation.md) [assign to @guocheng]
* [三大原则](https://github.com/camsong/redux-in-chinese/blob/master/docs/introduction/ThreePrinciples.md)[assign to @guocheng]
* [先前技术](https://github.com/camsong/redux-in-chinese/blob/master/docs/introduction/PriorArt.md)
* [生态](https://github.com/camsong/redux-in-chinese/blob/master/docs/introduction/Ecosystem.md)
* [示例](https://github.com/camsong/redux-in-chinese/blob/master/docs/introduction/Examples.md)

校对过程：

* 回复认领本 issue
* 把中文与原文对比阅读，对于有更新的内容做同步
* 完成后提交 PR 即可

**Comment by camsong** [comment]
@guocheng 是否有时间？

**Comment by guocheng** [comment]
@camsong 我来搞 动机 和 三大原则吧

**Comment by camsong** [comment]
好，这次是校对，原则上只需与原文更新同步即可，如果发现语法不顺的也请改一下。

**Comment by camsong** [comment]
@guocheng Added you to the `Collaborators` just now, thanks for your contribution :tada:

**Comment by guocheng** [comment]
@camsong 动机，三大原则已改完并提交
先前技术，生态，示例我来审阅吧，一会一并更新。

**Comment by camsong** [comment]
好的 :+1:

**Comment by guocheng** [comment]
已经都搞定了

**Comment by camsong** [comment]
仔细读了一遍，流畅多了，新内容也都同步了 :+1: 

建议新建一个分支操作，然后发 PR 让其它人 Review 后再合并

**Comment by guocheng** [comment]
本来我也是想PR的，结果push之后就直接进来了，没明白为什么。而且我在自己的库里点PR，github返回 There isn’t anything to compare.

**Comment by camsong** [comment]
哈哈，你是直接在 master 上改的，同一个分支没办法 PR。可以先 checkout 一个新分支，就可以 PR 到 master 了
