### ISSUE TITLE
Proofread『基础』章节

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#55]
为了译文提高质量，我们需定期对内容与原文做同步更新，本次校对的是『基础』章节，包括 6 小节内容。

## 基础

* [Action](https://github.com/camsong/redux-in-chinese/blob/master/docs/basics/Actions.md)
* [Reducer](https://github.com/camsong/redux-in-chinese/blob/master/docs/basics/Reducers.md)
* [Store](https://github.com/camsong/redux-in-chinese/blob/master/docs/basics/Store.md)
* [数据流](https://github.com/camsong/redux-in-chinese/blob/master/docs/basics/DataFlow.md)
* [搭配 React](https://github.com/camsong/redux-in-chinese/blob/master/docs/basics/UsageWithReact.md)
* [示例：Todo 列表](https://github.com/camsong/redux-in-chinese/blob/master/docs/basics/ExampleTodoList.md)

校对过程：

* 回复认领本 issue
* 把中文与原文对比阅读，对于有更新的内容做同步
* 完成后提交 PR 即可

**Comment by camsong** [comment]
@pandazki 有没有时间，部分也可

**Comment by pandazki** [comment]
最近时间有点紧，可能分成两个周末完成吧。

**Comment by dorayx** [comment]
这个我能帮忙么？

**Comment by camsong** [comment]
@dorayx 你来校对『高级』这一章，如何？

**Comment by owenyang0** [comment]
有一些简单的typo，可以直接提PR吗？

**Comment by camsong** [comment]
@omytea 可以，欢迎

**Comment by pandazki** [comment]
最近时间比较少，后三篇麻烦@yuweiw823 啦~

**Comment by yuweiw823** [comment]
好的没问题

**Comment by yuweiw823** [comment]
后三篇的校对和更新已经好了

**Comment by camsong** [comment]
:+1: @yuweiw823
