### ISSUE TITLE
Proofread『技巧』章节

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#58]
为了译文提高质量，我们需定期对内容与原文做同步更新，本次校对的是『技巧』章节，包括 6 小节内容。

## 技巧

* 迁移到 Redux
* 减少样板代码
* 服务端渲染
* 编写测试
* 计算衍生数据
* 实现撤销重做

校对过程：

* 回复认领本 issue
* 把中文与原文对比阅读，对于有更新的内容做同步
* 完成后提交 PR 即可

**Comment by yuweiw823** [comment]
今明两天内应该能搞定

**Comment by yuweiw823** [comment]
已完成。
