### ISSUE TITLE
将这个文档的MD展示的UI用的是什么框架或者项目？

### ISSUE THREAD

**Issue by jieyou** [camsong/redux-in-chinese#59]
RT，http://camsong.github.io/redux-in-chinese/docs/introduction/Motivation.html 所用的UI。
另外一个文档 https://fakefish.github.io/react-webpack-cookbook/Authoring-libraries.html 也是用的这个UI框架。
请告知名称？

**Comment by demohi** [comment]
[GitBook](https://www.gitbook.com/)
