### ISSUE TITLE
Proofread『高级』章节

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#60]
为了译文提高质量，我们需定期对内容与原文做同步更新，本次校对的是『高级』章节，包括 6 小节内容。

## 高级

* 异步 Action
* 异步数据流
* Middleware
* 搭配 React Router
* 示例：Reddit API
* 下一步

英文地址：https://github.com/rackt/redux/tree/master/docs/advanced

校对过程：

* 回复认领本 issue
* 把中文与英文对比阅读，同步更新内容
* 完成后提交 PR

**Comment by camsong** [comment]
@dorayx 有时间吗？

**Comment by jovey-zheng** [comment]
I'll try my best to do this.

**Comment by camsong** [comment]
@jovey-zheng :+1:
