### ISSUE TITLE
Proofread『词汇表』和『排错』

### ISSUE THREAD

**Issue by camsong** [camsong/redux-in-chinese#61]
为了译文提高质量，我们需定期对内容与原文做同步更新，本次校对的是『词汇表』和『排错』。

* [词汇表](https://github.com/rackt/redux/blob/master/docs/Glossary.md)
* [排错](https://github.com/rackt/redux/blob/master/docs/Troubleshooting.md)

校对过程：

* 回复认领本 issue
* 把中文与英文对比阅读，同步更新内容
* 完成后提交 PR

**Comment by camsong** [comment]
@dorayx 有时间吗？

**Comment by dorayx** [comment]
@camsong 可以哈，这周末弄下

**Comment by camsong** [comment]
我把你加入了 contributors，希望能持续贡献，一起翻译和 Review。Welcome :clap:

**Comment by dorayx** [comment]
@camsong 我同步好了，不过发现有些翻译有错别字以及不通顺的地方，是要一起 PR 还是分开呢？

**Comment by camsong** [comment]
如果不是这两篇相关的就新开 PR 吧
