### ISSUE TITLE
如何使用redux的容器组件

### ISSUE THREAD

**Issue by logzh** [camsong/redux-in-chinese#77]
一个页面需要一个container组件还是多个container组件？

如果是一个containner组件，那么它所有的的子组件都是展示组件，都是从顶部containner组件中接受props参数和action吗，这些展示组件是不是还需要一些自己的ui状态？

**Comment by camsong** [comment]
使用 `connect` 连接 state 的组件被称为 container 组件。
为了保证数据流向单一清晰，尽量只把顶层组件设置为 container 组件，通常是只有一个。如果顶层是多个 react-router 组件，我一般会把它们都设置为 container 组件。

但如果数据层级非常深，结构非常复杂，多个 container 组件我觉得是可以的。同时展示组件原则上是不应该有任何 state（包括 ui 状态也要全部放到 store 中）。

**Comment by logzh** [comment]
@camsong 明白，多谢！
