### ISSUE TITLE
smart component 和 dumb component 如何翻译？

### ISSUE THREAD

**Issue by omytea** [camsong/redux-in-chinese#8]
basics\UsageWithReact 這一節中

爲什麼不能直接寫 "聰明組件"和“傻組件”或者“笨組件” 木偶有什麼特殊的含義沒?

**Comment by camsong** [comment]
我也一直在纠结这个问题，为了翻译的时候尽量做到 “信达雅"。

首先，`smart` 大陆这里有基本都译作 `智能`，所以 `smart component` 翻译成 `智能组件` 没啥问题。
`dumb component` 与之对应，也试图做到 **4 字** 对应，所以没有译成 `傻`、`哑`、`笨`，感觉 `傻` 和 `笨` 不雅，没有考虑。

这是译作 `木偶` 的原因：`dumb` 发音是 `/dʌm/`, 本身有一个类似 `木` 的音，而且对应的名词 `dummy` 就是 `傀儡`、`木偶` 的意思；正好又 **4 字** 对应；而且 `dumb component` 就是指被父级完全控件的组件，和 `木偶` 有点像。

现在想到另一种译法，直接叫 `非智能组件`。直截了当，与 `smart component` 相对应，你觉得哪种好呢？

**Comment by omytea** [comment]
nah 雅不雅要考虑原文 原文不雅的话译文雅不雅有待商榷 而且太纠结于雅所以出不了dummy book(以及 dummy book也不是木偶书...)

智能在我的概念中代表着类似于交行机器人那样的玩意 一个component你硬给它扣这么大的帽子我觉得不妥

木偶的话作为读者的我的第一反应是 是不是有提线? 是不是有master/controller在后面? 只是修改state的smart component做不了那么多的事情 看了原文以后会觉得 "啊 原来原文用的并不是puppet 又是译者自己在作"

dumb其实是对应smart的反义词来着 精对应傻 智能对应不了木偶 
此外我翻译的部分也有部分被改成文邹邹的样子了 这个有空单开issue再议

雅的前提是 信和达 做不到信和达的话 不要考虑雅的问题 以上

**Comment by namelos** [comment]
以前多次看见过哑组件这种说法（非react相关）。不过个人感觉傀儡组件更容易理解些。
一般服务器有master slave之分。但是觉得翻译成主/从组件并不突出。
如果从实际含义来说应该是抽象组件和纯视图组件。而且irc里面看到有人会搞混抽象组件和高阶组件（用于composition）。
总得来说，还是觉得傀儡最容易理解。

**Comment by camsong** [comment]
@omytea  “智能” 并没有想像中那么高科技，现在基本是个中性词。高端的翻译是“智慧”，如 “smart city” 是 "智慧城市"。

smart/dumb 本身就是两个含糊的词，或者原作者也没有选这个词的时候也没想那么多。

dumb 翻译现在总结起来有这么几种：
1. 木偶
2. 傻
3. 笨
4. 傀儡
5. 哑（科技类通用译法）
6. 非智能（与智能相对）
7. dumb 不译

**Comment by omytea** [comment]
dumb 有木偶的义项我是不知道/没见到过 在wikipedia上查的还是muteness 和 stupidity 并没有doll或者puppet 

dummy倒是有 但我觉得一定要用引申义的话略牵强

----------------

@namelos 提到的翻译为哑 我认为可能是出自这里 https://en.wikipedia.org/wiki/Computer_terminal#Dumb_terminals

就是以前的那种局域网内一台服务器叫做smart terminal 其他终端无计算能力的dumb terminal  从smart上取结果这样 倒是有点类似 

但我认为这里的 dumb terminal 译为哑也有疑义 因为dumb terminal 并不是不能input output 而是不能process 所以还是傻 当初没有译为傻 大概是像 @camsong 说的"不雅"

---------------------

到 redux 这里的话 dumb component 也不能说完全不能process 更像是没有perception 但是一定不是哑因为可以 render

所以我还是 vote for 傻

**Comment by yanxyz** [comment]
将 smart 一律译为智能，实际上不大好。这里的意思即聪明与笨拙。

**Comment by camsong** [comment]
我现在更偏向于`智能`和`笨拙`，不选`傻瓜`是因为它是名词。这两个词现在还没有权威的翻译，我们翻译也就是想降低新手理解成本，直白点好。`木偶`引申意太多，所以不选。
如果没有更好的选择，暂就选这两个吧

**Comment by camsong** [comment]
`smart` 和 `dumb` 并不是描述模糊的词汇，这里在考虑换用更清晰的词，需要哪进一下
https://github.com/rackt/react-redux/issues/170

**Comment by camsong** [comment]
最终确认使用 **Presentational** 和 **Container** 这两个词。
分别译为 **展示型** 和  **容器型** 如何？有没有其它的建议

**Comment by tngan** [comment]
合併的時候：
容器組件 (Container components)
演示組件 (Presentational components)

分開的時候：
展示型/顯示型/演示型 (Presentational)
容器(Container) <- Container 本身已經是一個名詞了。

**Comment by camsong** [comment]
@tngan 谢谢你的建议。为了方便，我们统一一下：

合并的时间：
容器组件（Container components）
展示组件（Presentational components）

单独使用的时候：
容器型（Container）
展示型（Presentational）

欢迎提个 PR，@jovey-zheng

**Comment by jovey-zheng** [comment]
:+1: Good suggestion.
