### ISSUE TITLE
建议统一将 constant(s) 翻译成「常量」

### ISSUE THREAD

**Issue by zbinlin** [camsong/redux-in-chinese#80]
发现在不同的章节里，constant(s) 的翻译不一致，如：

* 第 2 章、第 7 章里翻译成「常量」
* 第 4.2 章里翻译成「定值」
* 第 6 章里翻译成「常数」

建议统一翻译为「常量」。

**Comment by camsong** [comment]
赞成！
有时间发个 PR 吗？

**Comment by camsong** [comment]
赞成！
有时间发个 PR 吗？

**Comment by zbinlin** [comment]
可以，稍晚点我发个 PR。
