### ISSUE TITLE
在 http://camsong.github.io/redux-in-chinese 这个网站中发现两处错误

### ISSUE THREAD

**Issue by liuyutao** [camsong/redux-in-chinese#90]
http://camsong.github.io/redux-in-chinese/docs/basics/ExampleTodoList.html 
在上面这个页面中。
1. 在 入口文件  index.js 中
   React.render(
  <Provider store={store}>
    {() => < App / >}
  </Provider>,
  rootElement
)
这里的< App/ > 外面应该没有{()=>}   
但是发现在repos中是没问题的，怀疑是不是没有重新生成呀。

2.另一处问题也同上。在
容器组件处 containers/App.js 处，最后一行没有显示出来。
export default connect(select)(App)
 在本git中也是正确的。所以怀疑重新生成一下应该就好了吧。

**Comment by camsong** [comment]
是的，刚发布一下就好了，Thanks
