### ISSUE TITLE
希望能翻译 redux-tutorial

### ISSUE THREAD

**Issue by transtone** [camsong/redux-in-chinese#97]
很好的redux入门教程，希望能翻译一下：
https://github.com/happypoulp/redux-tutorial

**Comment by camsong** [comment]
好建议，过几天我排下期，希望你也能参与

**Comment by transtone** [comment]
很乐意参与。内容虽不多，我也尝试过翻译几篇，但水平有限，有些专业名词翻译有问题，还有些英文本身都没理解的。

**Comment by camsong** [comment]
https://github.com/react-guide/redux-tutorial-cn/issues
