### ISSUE TITLE
url err `http://cn.redux.js.org/docs/basics/Action.md`

### ISSUE THREAD

**Issue by solome** [camsong/redux-in-chinese#99]
see http://cn.redux.js.org/docs/basics/Store.html

First paragraph, `在前面的章节中，我们学会了使用 action 来描述“发生了什么”`，`action` url should be http://cn.redux.js.org/docs/basics/Action.html ， not  http://cn.redux.js.org/docs/basics/Action.md。

**Comment by camsong** [comment]
Thanks for reporting this, can you raise a PR to fix this?
